name: Test Repository
on: push
jobs:
  test-code:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      
      - name: setup Python 
        uses: actions/setup-python@v5
        with: python-version: "3.12.1"
      
      - name: Install uv
        uses: astral-sh/setup-uv@v6
